### ISSUE TITLE
Screens section without “noise”

### ISSUE THREAD

**Issue by AndreSanctus** [batocera-linux/batocera-bezel#22]
Hi.
I have been using these bezels and I like them very much, however, I would like to have the bezels without “noise”/blur/effect in the screen section.

So, I’ve been editing them in Photoshop. I am deleting the screen section and make it totally transparent. This way the games are a lot more vivid and sharp (if we turn on the scanlines and curvature in Batocera).

I would like to know if you already have versions of these bezels the way I am describing. If not, I’ll be doing them for my use at least.

**Comment by lbrpdx** [comment]
The "unglazed" versions (fully transparent screens without glare/noise) are now the new default bezels. The old "glazed" bezels are available through Batocera content downloader, as an addition.

**Comment by lbrpdx** [comment]
With 5.27 released, I think we can close this ticket.

**Comment by lbrpdx** [comment]
Can anyone close this, please? I don't have the user rights to do it.
